#ifndef IU7_CPROG_LABS_2019_DMITRYKOVALEV_MEM_OPER_H
#define IU7_CPROG_LABS_2019_DMITRYKOVALEV_MEM_OPER_H

int change_mem(double **arr, int *n);

#endif //IU7_CPROG_LABS_2019_DMITRYKOVALEV_MEM_OPER_H
